name: Deploy doxygen

on:
  push:
    branches: ["main", "deploy-doc"]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install doxygen
        run: |
          wget https://www.doxygen.nl/files/doxygen-1.9.6.linux.bin.tar.gz
          tar xf doxygen-1.9.6.linux.bin.tar.gz
      - name: Build document
        run: |
          wget https://upload.cppreference.com/mwiki/images/f/f8/cppreference-doxygen-web.tag.xml
          ./doxygen-1.9.6/bin/doxygen
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./docs/html

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
